import type { Metadata } from "next";
import { Footer, Header, Sidebar } from "./main-sections";
import { Up } from "@/components";
import { getCourses, getServices } from "@/api/api";
import { MainInfo } from "@/interfaces/menu.interface";
import "./globals.css";
import style from "./layout.module.css";

export const metadata: Metadata = {
    title: "Next.js App",
    description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
    const courses = await getCourses();
    const services = await getServices();
    const books = [
        {
            _id: "1321safasfsa321",
            firstCategory: "books",
            pages: [
                {
                    _id: "asf4as65f4a654f",
                    alias: "alias",
                    title: "title",
                    category: "category",
                },
            ],
        },
    ];
    const products = [
        {
            _id: "1321safasfsa321",
            firstCategory: "products",
            pages: [
                {
                    _id: "asf4as65f4a654f",
                    alias: "alias",
                    title: "title",
                    category: "category",
                },
            ],
        },
    ];

    const mainInfo: MainInfo = {
        courses,
        services,
        books,
        products,
    };

    return (
        <html lang="en">
            <head></head>
            <body className={style.gridContainer}>
                <Header {...mainInfo} />
                <nav className={style.sidebar}>
                    <Sidebar {...mainInfo} />
                </nav>
                <Footer />
                <main className={style.main}>{children}</main>
                <Up />
            </body>
        </html>
    );
}
