name: Publish Docker

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: Publish to Registry
              uses: elgohr/Publish-Docker-Github-Action@v4
              with:
                  registry: docker.pkg.github.com
                  name: docker.pkg.github.com/Sandrixman/first-Next.js-project/first-Next.js-project
                  username: ${{secrets.DOCKER_USERNAME}}
                  password: ${{secrets.DOCKER_PASSWORD}}
                  tags: "develop"
